### ISSUE TITLE
CP13 - El mail es inválido

### ISSUE THREAD

**Issue by psanguinet** [psanguinet/IS2#1]
Alta de usuario: Durante el alta de usuario, al ingresar un mail válido, el sistema lanza el error "El mail es invalido". Se adjunta screenshot.

![20150614_errormail](https://cloud.githubusercontent.com/assets/12678030/8151024/c3b775e8-12d7-11e5-9e9c-e71f3ca29492.png)

**Comment by acanabarro** [comment]
Ticket pasa a Done

**Comment by psanguinet** [comment]
El error no fue solucionado. Segun lo reportado por Andrés, problemas al realizar el merge entre la rama Desarrollo_Andres y Master no se impactaron los cambios.

**Comment by acanabarro** [comment]
Ticket Done

**Comment by psanguinet** [comment]
Resuelto
