### ISSUE TITLE
CP1 - Alta de usuario

### ISSUE THREAD

**Issue by psanguinet** [psanguinet/IS2#2]
Luego de hacer un alta de usuario correcta. El sistema, luego de presionar aceptar en el diálogo que muestra "Usuario agregado correctamente" debería limpiar el formulario para ingresar otro usuario o volver al listado de usuarios, mostrando el nuevo usuario agregado.

![20150614_comportamiento en alta de usuario](https://cloud.githubusercontent.com/assets/12678030/8151118/9b9f32f0-12da-11e5-8353-27cea3c006ef.png)

![20150614_comportamiento en alta de usuario 2](https://cloud.githubusercontent.com/assets/12678030/8151133/379ebd4c-12db-11e5-824c-7865f7743cc7.png)

**Comment by psanguinet** [comment]
El error no fue solucionado. Segun lo reportado por Andrés, problemas al realizar el merge entre la rama Desarrollo_Andres y Master no se impactaron los cambios.

**Comment by acanabarro** [comment]
Ticket Done

**Comment by psanguinet** [comment]
Resuelto
