### ISSUE TITLE
Botón siguiente

### ISSUE THREAD

**Issue by acanabarro** [psanguinet/IS2#3]
![btn siguiente](https://cloud.githubusercontent.com/assets/12687062/8151949/1c534e10-12ed-11e5-90a7-5cb94f1ac66a.png)

Una vez que se activa el botón siguiente si se cambia la búsqueda este no se desactiva permitiendo al usuario presionarlo y que se caiga el programa. Se adjunta captura.

**Comment by psanguinet** [comment]
Tiket pasa a Doing

**Comment by psanguinet** [comment]
Tiket pasa a Done

**Comment by acanabarro** [comment]
![image](https://cloud.githubusercontent.com/assets/12687062/8176735/e1d6561e-13d3-11e5-823b-359668d1ab76.png)

Persiste el error en el caso de continuar buscando por el mismo tipo de busqueda. Es decir, si estoy buscando un producto por nombre que tiene varios resultados aparece el boton siguiente, luego busco por otro nombre y el boton siguiente no desaparece provocando la caida al presionar dicho botón. Se adjunta imagen.

**Comment by psanguinet** [comment]
Tiket pasa a Doing

**Comment by psanguinet** [comment]
Tiket pasa a Done
