### ISSUE TITLE
Borrar usuario

### ISSUE THREAD

**Issue by acanabarro** [psanguinet/IS2#5]
![borrar usuario](https://cloud.githubusercontent.com/assets/12687062/8152030/4f5b5d4c-12ee-11e5-85e0-6383e2eb4545.png)

Al borrar un usuario se cierra la ventana y no se notifica al usuario que se logro borrar.

**Comment by psanguinet** [comment]
Tiket pasa a Doing

**Comment by psanguinet** [comment]
Tiket pasa Done

**Comment by acanabarro** [comment]
Mensaje notifica eliminación de usuario pero falta que se vuelva a mostrar la lista de usuarios actualizada.

**Comment by psanguinet** [comment]
Resuelto
