### ISSUE TITLE
CP13 - Modificar Usuario - El mail es inválido

### ISSUE THREAD

**Issue by psanguinet** [psanguinet/IS2#7]
El mensaje debería mostrar "El mail es requerido" o "El mail no puede ser vacío"
![20150614_cp13_modificacionusuario_mailvacio](https://cloud.githubusercontent.com/assets/12678030/8172195/983aae22-1394-11e5-99a8-f5366880d91b.png)

**Comment by acanabarro** [comment]
Ticket pasa a Done

**Comment by psanguinet** [comment]
El error no fue solucionado. Segun lo reportado por Andrés,  problemas al realizar el merge entre la rama Desarrollo_Andres y Master no se impactaron los cambios.

**Comment by acanabarro** [comment]
Ticket Done

**Comment by psanguinet** [comment]
Resuelto.
